version: 2
jobs:
  build:
    resource_class: large
    docker:
      - image: circleci/android:api-28
        environment:
          ANDROID_HOME: /home/circleci/android
          CIRCLE_JDK_VERSION: oraclejdk8
    steps:
      - checkout
      - run:
          name: Verify configuration changes (only Segment employees are allowed to do them)
          command: |
            set -e
            wget -qO - https://raw.githubusercontent.com/segmentio/analytics-android-integrations/master/.circleci/config.yml | cmp - .circleci/config.yml
      - run:
          name: Create folders
          command: mkdir -p /home/circleci/android/licenses
      - restore_cache:
          key: dependencies-{{ checksum "build.gradle" }}
      - run:
          name: Accept licenses
          command: cp /opt/android/sdk/licenses/* $ANDROID_HOME/licenses
      - run:
          name: Install dependencies
          command: ./gradlew dependencies
      - run:
          name: Linter
          command: ./gradlew lint spotlessCheck
      - run:
          name: Run tests
          command: ./gradlew check test --profile
      - save_cache:
          key: dependencies-{{ checksum "build.gradle" }}
          paths:
            - /home/circleci/.android
            - /home/circleci/android
            - /home/circleci/.gradle
            - /usr/local/android-sdk-linux/platforms/android-28
            - /usr/local/android-sdk-linux/build-tools/28.0.0
            - /usr/local/android-sdk-linux/extras/android/m2repository
      - store_artifacts:
          path: build/reports/profile/
          destination: reports

workflows:
  version: 2
  run:
    jobs:
      - build:
          filters:
            tags: 
              only: /.*/